function  WWHBookData_AddTOCEntries(P)
{
var A=P.fN("Welcome to the EAGLE Online Help","0");
A=P.fN("Online Help Tips","1");
A=P.fN("Application Support","2");
A=P.fN("Getting Started with EAGLE","3");
var B=A.fN("About EAGLE","4");
B=A.fN("EAGLE\u2019s Opening Page","5");
B=A.fN("Logging In","6");
var C=B.fN("Accepting EAGLE Provisions","7");
B=A.fN("EAGLE Home Page","8");
C=B.fN("EAGLE Menu","9");
C=B.fN("EAGLE Tabs","10");
C=B.fN("EAGLE Blue Panel","11");
B=A.fN("Application Support","12");
B=A.fN("Logging Out","13");
A=P.fN("Analysis","14");
B=A.fN("Analysis Overview","15");
B=A.fN("Performing a Class Comparison","16");
C=B.fN("F-test: One Way ANOVA","17");
C=B.fN("GLM or Generalized Linear Model Details","18");
A=P.fN("Viewing Results","19");
B=A.fN("Results Overview","20");
B=A.fN("Class Comparison Report","21");
C=B.fN("Resorting Column Results","22");
C=B.fN("Showing Additional Information","23");
C=B.fN("Downloading a Report","24");
C=B.fN("Paging Through a Report","25");
C=B.fN("Displaying Comparison Groups","26");
A=P.fN("Managing Lists","27");
B=A.fN("Managing Lists Overview","28");
B=A.fN("Adding New Lists","29");
C=B.fN("Combining Existing Lists to Create a New List","30");
B=A.fN("Viewing the Data Items in a List","31");
B=A.fN("Removing Data Items","32");
B=A.fN("Deleting an Entire List","33");
B=A.fN("Exporting a List","34");
A=P.fN("Glossary","35");
}
