function  WWHBookData_Files(P)
{
P.fA("Welcome to the EAGLE Online Help","Welcome.1.1.html");
P.fA("Online Help Tips","OnlineHelpBoilerplate.2.1.html");
P.fA("Application Support","Application%20Support.3.1.html");
P.fA("Getting Started with EAGLE","Eagle_Getting_Started.4.1.html");
P.fA("About EAGLE","Eagle_Getting_Started.4.2.html");
P.fA("EAGLE\u2019s Opening Page","Eagle_Getting_Started.4.3.html");
P.fA("Logging In","Eagle_Getting_Started.4.4.html");
P.fA("Accepting EAGLE Provisions","Eagle_Getting_Started.4.5.html");
P.fA("EAGLE Workspace","Eagle_Getting_Started.4.6.html");
P.fA("EAGLE Menu","Eagle_Getting_Started.4.7.html");
P.fA("EAGLE Main Menu and Tabs","Eagle_Getting_Started.4.8.html");
P.fA("EAGLE Side Bar","Eagle_Getting_Started.4.9.html");
P.fA("Application Support","Eagle_Getting_Started.4.10.html");
P.fA("Logging Out","Eagle_Getting_Started.4.11.html");
P.fA("Advanced Search","Eagle_Adv_Search.5.1.html");
P.fA("Advanced Search Overview","Eagle_Adv_Search.5.2.html");
P.fA("Performing an Epidemiology (EPI) Query","Eagle_Adv_Search.5.3.html");
P.fA("Performing an SNP Query","Eagle_Adv_Search.5.4.html");
P.fA("Analysis","Eagle_High_Order_Analysis.6.1.html");
P.fA("Analysis Overview","Eagle_High_Order_Analysis.6.2.html");
P.fA("Performing a Class Comparison","Eagle_High_Order_Analysis.6.3.html");
P.fA("F-test: One Way ANOVA Details","Eagle_High_Order_Analysis.6.4.html");
P.fA("GLM or Generalized Linear Model Details","Eagle_High_Order_Analysis.6.5.html");
P.fA("ANOVA Details","Eagle_High_Order_Analysis.6.6.html");
P.fA("Managing Lists","Eagle_Manage_Lists.7.1.html");
P.fA("Managing Lists Overview","Eagle_Manage_Lists.7.2.html");
P.fA("Adding New Lists","Eagle_Manage_Lists.7.3.html");
P.fA("Combining Existing Lists to Create a New List","Eagle_Manage_Lists.7.4.html");
P.fA("Viewing the Data Items in a List","Eagle_Manage_Lists.7.5.html");
P.fA("Removing Data Items","Eagle_Manage_Lists.7.6.html");
P.fA("Deleting an Entire List","Eagle_Manage_Lists.7.7.html");
P.fA("Exporting a List","Eagle_Manage_Lists.7.8.html");
P.fA("Filtering a List (Blood, Tissue Normal, Tissue Cancer)","Eagle_Manage_Lists.7.9.html");
P.fA("Viewing Results","Eagle_View%20Results.8.1.html");
P.fA("View Results Overview","Eagle_View%20Results.8.2.html");
P.fA("Epidemiology (EPI) Query Report","Eagle_View%20Results.8.3.html");
P.fA("Filtering the EPI Report","Eagle_View%20Results.8.4.html");
P.fA("Saving Samples to a PatientDID List (EPI Report)","Eagle_View%20Results.8.5.html");
P.fA("SNP Query Report","Eagle_View%20Results.8.6.html");
P.fA("Class Comparison Report","Eagle_View%20Results.8.7.html");
P.fA("Resorting Column Results","Eagle_View%20Results.8.8.html");
P.fA("Showing Additional Information","Eagle_View%20Results.8.9.html");
P.fA("Downloading a Report","Eagle_View%20Results.8.10.html");
P.fA("Paging Through a Report","Eagle_View%20Results.8.11.html");
P.fA("Displaying Comparison Groups","Eagle_View%20Results.8.12.html");
P.fA("Glossary","Eagle_Glossary.9.1.html");
}
