function FileData_Pairs(x)
{
x.t("managing","lists");
x.t("lists","managing");
x.t("lists","create");
x.t("lists","eagle");
x.t("lists","adding");
x.t("create","new");
x.t("default","patientdid");
x.t("new","lists");
x.t("new","list");
x.t("new","patientdid");
x.t("list","following:");
x.t("patientdid","lists");
x.t("patientdid","list");
x.t("provides","collection");
x.t("collection","default");
x.t("eagle","provides");
x.t("combining","existing");
x.t("existing","lists");
x.t("following:","combining");
x.t("adding","new");
}
