function FileData_Pairs(x)
{
x.t("table.","remove");
x.t("lists","patients");
x.t("legend","indicates");
x.t("legend","indicators");
x.t("certain","types");
x.t("indicates","certain");
x.t("reside","table.");
x.t("results","epidemiology");
x.t("remove","legend");
x.t("comparison","group.");
x.t("comparison","report");
x.t("indicators","click");
x.t("patients","fulfilling");
x.t("specifications","epi");
x.t("display","members");
x.t("display","epi");
x.t("(epi)","query");
x.t("members","comparison");
x.t("viewing","results");
x.t("group.","legend");
x.t("report","display");
x.t("report","viewing");
x.t("report","page");
x.t("report","epidemiology");
x.t("types","information");
x.t("query.","class");
x.t("click","legend");
x.t("page","lists");
x.t("query","report");
x.t("information","reside");
x.t("epidemiology","(epi)");
x.t("epidemiology","query");
x.t("epi","report");
x.t("epi","query.");
x.t("fulfilling","specifications");
x.t("class","comparison");
}
