function FileData_Pairs(x)
{
x.t("right","left");
x.t("left","arrow");
x.t("steps.","click");
x.t("results","follow");
x.t("results","class");
x.t("comparison","report");
x.t("arrow","click");
x.t("viewing","results");
x.t("number","report");
x.t("report","viewing");
x.t("report","page");
x.t("report","information");
x.t("report","paging");
x.t("follow","steps.");
x.t("click","right");
x.t("click","page");
x.t("page","results");
x.t("page","number");
x.t("information","class");
x.t("paging","report");
x.t("class","comparison");
}
