function FileData_Pairs(x)
{
x.t("residing","comparison");
x.t("listed","first.");
x.t("first.","epi");
x.t("appears.","epidemiology");
x.t("group","listed");
x.t("group","follow");
x.t("group","name.");
x.t("steps.","comparison");
x.t("results","class");
x.t("comparison","group");
x.t("comparison","report");
x.t("comparison","groups");
x.t("area","click");
x.t("patients","residing");
x.t("display","patients");
x.t("(epi)","query");
x.t("viewing","results");
x.t("report","appears.");
x.t("report","displaying");
x.t("follow","steps.");
x.t("groups","area");
x.t("groups","display");
x.t("groups","viewing");
x.t("groups","displaying");
x.t("click","group");
x.t("baseline","group");
x.t("query","report");
x.t("epidemiology","(epi)");
x.t("displaying","comparison");
x.t("epi","query");
x.t("name.","baseline");
x.t("class","comparison");
}
