function FileData_Pairs(x)
{
x.t("email","information.");
x.t("getting","started");
x.t("button.","login");
x.t("need","username");
x.t("logging","getting");
x.t("logging","logging");
x.t("logging","log");
x.t("started","eagle");
x.t("legal","rules");
x.t("eagle","need");
x.t("eagle","logging");
x.t("information.","login");
x.t("login","button.");
x.t("login","panel");
x.t("login","successful");
x.t("enter","username");
x.t("click","login");
x.t("road","page");
x.t("rules","road");
x.t("username","password.");
x.t("username","password");
x.t("panel","enter");
x.t("page","appears");
x.t("received","email");
x.t("successful","legal");
x.t("password.","received");
x.t("password","click");
x.t("log","eagle");
}
