function FileData_Pairs(x)
{
x.t("type","heading");
x.t("advanced","search");
x.t("link","start");
x.t("start","defining");
x.t("results","review");
x.t("results","page");
x.t("overview","advanced");
x.t("enables","define");
x.t("search","type");
x.t("search","advanced");
x.t("search","overview");
x.t("search","page");
x.t("search","generates");
x.t("defining","query:");
x.t("queries","based");
x.t("review","view");
x.t("(epi)","query");
x.t("select","advanced");
x.t("define","queries");
x.t("heading","click");
x.t("performing","epidemiology");
x.t("click","link");
x.t("view","results");
x.t("page","enables");
x.t("page","epidemiology");
x.t("query","advanced");
x.t("query","report");
x.t("query","performing");
x.t("epidemiology","(epi)");
x.t("query:","epidemiology");
x.t("based","specifications.");
x.t("specifications.","select");
x.t("generates","results");
}
