function FileData_Pairs(x)
{
x.t("home","page");
x.t("getting","started");
x.t("access","eagle");
x.t("tabs.","eagle");
x.t("menu","home");
x.t("menu","eagle");
x.t("menu","tabs");
x.t("enables","quick");
x.t("started","eagle");
x.t("quick","access");
x.t("functions","eagle");
x.t("functions","information.");
x.t("side","bar");
x.t("eagle","menu");
x.t("eagle","functions");
x.t("eagle","side");
x.t("eagle","eagle");
x.t("eagle","workspace");
x.t("eagle","main");
x.t("workspace","getting");
x.t("workspace","enables");
x.t("workspace","eagle");
x.t("information.","access");
x.t("main","menu");
x.t("page","tabs.");
x.t("tabs","eagle");
}
