function FileData_Pairs(x)
{
x.t("describes","reports");
x.t("results","overview");
x.t("results","viewing");
x.t("results","eagle");
x.t("results","section");
x.t("overview","class");
x.t("high","order");
x.t("comparison","report");
x.t("search","results");
x.t("(epi)","query");
x.t("viewing","results");
x.t("eagle","returns");
x.t("report","epidemiology");
x.t("section","describes");
x.t("section","include");
x.t("reports","search");
x.t("include","following:");
x.t("query","report");
x.t("epidemiology","(epi)");
x.t("analyses.","topics");
x.t("topics","section");
x.t("following:","results");
x.t("order","analyses.");
x.t("class","comparison");
x.t("returns","high");
}
