function FileData_Pairs(x)
{
x.t("describes","perform");
x.t("advanced","search");
x.t("advanced","query");
x.t("overview","performing");
x.t("include:","advanced");
x.t("perform","advanced");
x.t("search","advanced");
x.t("search","overview");
x.t("search","section");
x.t("(epi)","query");
x.t("eagle","data.");
x.t("section","describes");
x.t("section","include:");
x.t("data.","topics");
x.t("performing","epidemiology");
x.t("query","eagle");
x.t("epidemiology","(epi)");
x.t("topics","section");
}
