function FileData_Pairs(x)
{
x.t("user","session.");
x.t("shows","collection");
x.t("results","results");
x.t("results","overview");
x.t("results","page");
x.t("overview","results");
x.t("overview","viewing");
x.t("overview","view");
x.t("viewed","particular");
x.t("previously","viewed");
x.t("comparison","report");
x.t("allows","compare");
x.t("collection","reports");
x.t("viewing","results");
x.t("particular","user");
x.t("windows.","information");
x.t("session.","allows");
x.t("reports","previously");
x.t("reports","opening");
x.t("view","results");
x.t("opening","separate");
x.t("page","shows");
x.t("separate","windows.");
x.t("information","class");
x.t("class","comparison");
x.t("compare","reports");
}
