function FileData_Pairs(x)
{
x.t("download","report");
x.t("file","downloading");
x.t("group","group");
x.t("group","name");
x.t("results","class");
x.t("name","report.");
x.t("name","report");
x.t("comparison","group");
x.t("comparison","report");
x.t("comparison","groups");
x.t("display","members");
x.t("members","comparison");
x.t("viewing","results");
x.t("report.","download");
x.t("report","comparison");
x.t("report","display");
x.t("report","viewing");
x.t("report","generate");
x.t("report","spreadsheet");
x.t("report","displaying");
x.t("groups","comparison");
x.t("generate","class");
x.t("spreadsheet","file");
x.t("displaying","comparison");
x.t("downloading","report");
x.t("class","comparison");
}
