function FileData_Pairs(x)
{
x.t("interfaces","navigation");
x.t("support","logging");
x.t("getting","started");
x.t("features","used");
x.t("common","features");
x.t("pages.","topics");
x.t("include:","eagle");
x.t("logging","eagle");
x.t("introduces","eagle");
x.t("started","eagle");
x.t("eagle","interfaces");
x.t("eagle","getting");
x.t("eagle","eagle");
x.t("eagle","eagle\u2019s");
x.t("eagle","workspace");
x.t("eagle","section");
x.t("eagle\u2019s","opening");
x.t("workspace","application");
x.t("section","include:");
x.t("section","introduces");
x.t("opening","page");
x.t("page","logging");
x.t("application","support");
x.t("topics","section");
x.t("navigation","common");
x.t("used","pages.");
}
