function FileData_Pairs(x)
{
x.t("describes","eagle");
x.t("comparisons.","topics");
x.t("overview","performing");
x.t("include:","analysis");
x.t("eagle","run");
x.t("section","describes");
x.t("section","include:");
x.t("analyses","including");
x.t("performing","class");
x.t("topics","section");
x.t("run","analyses");
x.t("class","comparisons.");
x.t("class","comparison");
x.t("analysis","overview");
x.t("analysis","section");
x.t("analysis","analysis");
x.t("including","class");
}
