function FileData_Pairs(x)
{
x.t("describes","eagle");
x.t("getting","started");
x.t("access","eagle");
x.t("menu","eagle");
x.t("enables","quick");
x.t("started","eagle");
x.t("quick","access");
x.t("side","bar");
x.t("eagle","menu");
x.t("eagle","enables");
x.t("eagle","side");
x.t("eagle","eagle");
x.t("eagle","workspace");
x.t("eagle","information:");
x.t("eagle","tabs");
x.t("workspace","describes");
x.t("workspace","getting");
x.t("workspace","eagle");
x.t("workspace","comprises");
x.t("comprises","following:");
x.t("information:","workspace");
x.t("following:","eagle");
x.t("tabs","eagle");
}
