function FileData_Pairs(x)
{
x.t("results","review");
x.t("results","page");
x.t("overview","eagle");
x.t("overview","analysis");
x.t("gene","expression");
x.t("buttons","high");
x.t("high","order");
x.t("analyze","gene");
x.t("comparison","high");
x.t("comparison","report");
x.t("comparison","analysis");
x.t("filtering","normalization");
x.t("further","analyze");
x.t("review","view");
x.t("preprocessed","gene");
x.t("eagle","stores");
x.t("normalization","click");
x.t("stores","preprocessed");
x.t("data.","class");
x.t("performing","class");
x.t("click","following");
x.t("view","results");
x.t("expression","data.");
x.t("expression","data");
x.t("page","class");
x.t("data","filtering");
x.t("order","analysis");
x.t("following","buttons");
x.t("class","comparison");
x.t("analysis","overview");
x.t("analysis","performing");
x.t("analysis","analysis");
x.t("analysis","pageto");
x.t("analysis","generates");
x.t("pageto","further");
x.t("generates","results");
}
