function FileData_Pairs(x)
{
x.t("version","eagle");
x.t("user","guide");
x.t("download","online");
x.t("support","menu");
x.t("getting","started");
x.t("complete","eagle");
x.t("menu","option.");
x.t("guide","user");
x.t("guide","menu");
x.t("obtain","eagle");
x.t("enables","perform");
x.t("perform","following");
x.t("eagle.","display");
x.t("started","eagle");
x.t("option.","download");
x.t("option.","obtain");
x.t("display","complete");
x.t("eagle\u2019s","opening");
x.t("eagle","eagle\u2019s");
x.t("eagle","applicaton");
x.t("eagle","online");
x.t("eagle","user\u2019s");
x.t("tasks:","log");
x.t("applicaton","help");
x.t("opening","page");
x.t("page","getting");
x.t("page","enables");
x.t("page","eagle\u2019s");
x.t("online","version");
x.t("online","help");
x.t("help","support");
x.t("help","menu");
x.t("help","help");
x.t("following","tasks:");
x.t("log","eagle.");
x.t("user\u2019s","guide");
}
