function FileData_Pairs(x)
{
x.t("columns","show");
x.t("shows","selected");
x.t("type","snp");
x.t("designated","group.");
x.t("snp","identifier.");
x.t("snp","query");
x.t("snp","call");
x.t("group","snp");
x.t("identifier.","columns");
x.t("results","snp");
x.t("counts","type");
x.t("selected","patient");
x.t("viewing","results");
x.t("report","snp");
x.t("report","viewing");
x.t("report","page");
x.t("page","shows");
x.t("show","counts");
x.t("query","report");
x.t("patient","group");
x.t("call","designated");
}
