function FileData_Pairs(x)
{
x.t("download","report");
x.t("open","file.");
x.t("file","follow");
x.t("upper","right-hand");
x.t("results","class");
x.t("right-hand","corner.");
x.t("name","save");
x.t("comparison","report");
x.t("steps:","click");
x.t("button","upper");
x.t("viewing","results");
x.t("corner.","specify");
x.t("whether","save");
x.t("report","download");
x.t("report","viewing");
x.t("report","spreadsheet");
x.t("report","downloading");
x.t("follow","steps:");
x.t("click","button");
x.t("enter","name");
x.t("spreadsheet","file");
x.t("spreadsheet","file.");
x.t("save","open");
x.t("save","spreadsheet");
x.t("downloading","report");
x.t("class","comparison");
x.t("file.","enter");
x.t("specify","whether");
}
