function FileData_Pairs(x)
{
x.t("interfaces","navigation");
x.t("home","page");
x.t("support","logging");
x.t("getting","started");
x.t("features","used");
x.t("common","features");
x.t("pages.","topics");
x.t("include:","eagle");
x.t("logging","eagle");
x.t("introduces","eagle");
x.t("started","eagle");
x.t("eagle","interfaces");
x.t("eagle","home");
x.t("eagle","getting");
x.t("eagle","pages.");
x.t("eagle","eagle");
x.t("eagle","eagle\u2019s");
x.t("eagle","section");
x.t("eagle\u2019s","opening");
x.t("section","include:");
x.t("section","introduces");
x.t("opening","page");
x.t("page","logging");
x.t("page","application");
x.t("application","support");
x.t("topics","section");
x.t("navigation","common");
x.t("used","eagle");
}
