function FileData_Pairs(x)
{
x.t("user","session.");
x.t("shows","collection");
x.t("snp","query");
x.t("results","overview");
x.t("results","view");
x.t("results","page");
x.t("overview","viewing");
x.t("overview","view");
x.t("viewed","particular");
x.t("previously","viewed");
x.t("comparison","report");
x.t("allows","compare");
x.t("(epi)","query");
x.t("collection","reports");
x.t("viewing","results");
x.t("particular","user");
x.t("report","snp");
x.t("report","class");
x.t("windows.","reports");
x.t("session.","allows");
x.t("reports","previously");
x.t("reports","include");
x.t("reports","opening");
x.t("include","following:");
x.t("view","results");
x.t("opening","separate");
x.t("page","shows");
x.t("separate","windows.");
x.t("query","report");
x.t("epidemiology","(epi)");
x.t("following:","epidemiology");
x.t("class","comparison");
x.t("compare","reports");
}
