function FileData_Pairs(x)
{
x.t("creation","management");
x.t("managing","lists");
x.t("lists","managing");
x.t("lists","lists");
x.t("lists","overview");
x.t("lists","further");
x.t("lists","function");
x.t("lists","heading.");
x.t("lists","displayed");
x.t("lists","page");
x.t("lists","manage");
x.t("refine","queries");
x.t("working","lists");
x.t("clicking","patientdid");
x.t("overview","managing");
x.t("overview","eagle");
x.t("centralizes","activities");
x.t("patientdid","lists");
x.t("further","refine");
x.t("analysis.","working");
x.t("study-defined","patientdid");
x.t("queries","facilitate");
x.t("number","lists");
x.t("eagle","manage");
x.t("function","centralizes");
x.t("user-defined","study-defined");
x.t("pertaining","creation");
x.t("displayed","clicking");
x.t("page","minimize");
x.t("facilitate","analysis.");
x.t("activities","pertaining");
x.t("manage","lists");
x.t("management","user-defined");
x.t("minimize","number");
}
